### ISSUE TITLE
Missing layers.md and a few others

### ISSUE THREAD

**Issue by shentino** [ChatTheatre/SkotOS-Doc#4]
Oy!  Noah, you kinda nuked my docs a bit from the SkotOS repo

**Comment by noahgibbs** [comment]
Some of it moved. There's content in lpc-doc/dgd/functions.md and lpc-doc/dgd/errors.md (both in the lpc-doc repo) that's the same as the later parts of docs/dgd/layers.md.

But you're right, I removed some of layers.md (rather than dgd/layers.md) that I think was useful. I'm adding that file back in a PR right now. Thanks!

**Comment by shentino** [comment]
Could you double check the current version against the one you removed from the SkotOS repo?  The content restored doesn't completely match the content that was removed from the other repo.  In particular some stuff about fatal errors in DGD.

**Comment by shentino** [comment]
I also wanted to note that the version I originally wrote was meant to consolidate all of those into a combined summary version fit to be used as a general overview.
Honestly I wish you'd checked with me first before you just nuked it.

**Comment by noahgibbs** [comment]
All right. It's in Git history still, I'm not opposed to supplementing or replacing the current version.

**Comment by shentino** [comment]
For the time being could you restore layers.md back to its original condition and wipe anything you moved to elsewhere?

**Comment by noahgibbs** [comment]
So, right now the SkotOS-Doc repository contains all the files that used to be in docs, layers.md included, in the condition they were in there.

In other words I think they *are* in place at this point. Is that not what you're seeing?

**Comment by noahgibbs** [comment]
Or are you asking if I can put the docs directory back in the SkotOS repo and merge the SkotOS-Doc repo back in? We have a separate docs repo basically because we need to do that for some of the other ones, so we decided to do the same with the SkotOS repo. But it's just the file organisation -- the files still exist, just in a new repo.

**Comment by shentino** [comment]
What I mean is that you messed up layers.md not just by deleting it but also by splitting it up into separate files.

**Comment by noahgibbs** [comment]
Ah, okay. And you want anything else similar to be deleted, not just layers.md to be restored.

I believe that layers.md is currently (in SkotOS-Doc) the exact same as the file you checked in back in August. I copied the old one out of the SkotOS repo and it *should* be byte-for-byte the same as current one unless I made a mistake. I just went back and verified again and it appears to be the exact same.

**Comment by noahgibbs** [comment]
Hm. Okay, architecture.md includes stuff from there. And part of the reason I handled it the way I did is that there were multiple architecture/layers documents and layers.md does *not* include all the layers found in several of them.

So is your intent that layers.md would include all of that going forward, and it should be expanded?

**Comment by shentino** [comment]
Basically restore layers.md to mint condition the way I had it and by implication deleting anything elsewhere that got pulled from it.  Some of the relocated bits look a little awkward now for example now that they're taken out of context.

**Comment by shentino** [comment]
I don't remember if I mentioned this but layers.md was meant to be a stand-alone overview and IIRC either shannon or chris specifically asked me to document it.

**Comment by noahgibbs** [comment]
Okay. So if its purpose is to be "all the layers", then when I delete other stuff that has information not currently in it, is the intent that I would expand layers.md? Because it's not going to work well as an eternal and definitive document. It is clearly incomplete. And if one document is intended to be all the architectural documentation for all layers in the long term, it is going to be a very large and unfocused document.

**Comment by shentino** [comment]
I don't have time to fight over this, just do what you want.
